### PR TITLE
CF11 compatibilty added

### PR DESCRIPTION
**Pull request by sanaullah**
CF11 compatibilty added

### CODE REVIEW

**Comment by jclausen** [comment]
Thanks @sanaullah .  A few questions:

Since you didn't use `git mv` to move the module files, I can't diff the changes very well.  Was any of the code changed in the former `/models` directory - now `/modules/cbmongodb/models`?  

Also, it looks like you haven't merged the latest changes from the upstream dev branch.  The new version is 3.2.0.4 and the pull you're submitting is for v. 3.2.0.3.  You can see this PR with those changes (some of which you probably have in your fork):  https://github.com/jclausen/cbmongodb/pull/9

Thanks and let me know on the changes to the former models directory.  If there few to none of those, it should be an easy merge.  
- J

**Comment by sanaullah** [comment]
Hi Jon,

I think I have copied changes from 3.2.0.4 and moved files but lot of changes so github not displaying correctly.

1:
https://github.com/sanaullah/cbmongodb/archive/development.zip
copy following files into your existing  structure, I am using SmartGit which displays difference for each file.
modules/cbmongodb
    ModuleConfig.cfc
    models/_._

2:
If you have some time then just try code for testing.

3: 
create new branch in git cf11 then i will create pull request for new branch ( so all new changes will be completely in separate branch )

4: unit tests some of them still needs fixes, CF11 return (coldfusion.runtime.java.JavaProxy) and  Lucee return (lang.Class)
also DirectoryList function in cf1 is different (seems like cf don't accept named params)

**Comment by jclausen** [comment]
I'm going to test this tonight.  No need to create a new branch just yet.  It looks like much of what you've done will be easy to get back up and passing tests.

Will update you soon.  Thanks!

**Comment by jclausen** [comment]
@sanaullah can you push those changes from 3.2.0.4 up in to your PR branch, so I can review everything at once?

**Comment by sanaullah** [comment]
I copied all changes from this commit
https://github.com/jclausen/cbmongodb/commit/0acd9104b2b6970769bf4111054954462409d744

**Comment by jclausen** [comment]
@sanaullah:  On Line 18 of `tests/unit/testsMongoCollection.cfc` you added a `fix()` around `now()`:

Yours:

```
{"iteration":i,"date":javacast('java.util.Date',fix(now())),"boolean": javacast('boolean',i-i),"textString":"I am record number #i# in the collection"}
```

Original:

```
{"iteration":i,"date":javacast('java.util.Date',now()),"boolean": javacast('boolean',i-i),"textString":"I am record number #i# in the collection"}
```

This breaks Lucee compat for the tests because of Java casting issues. Do you remember the error that CF11 was throwing that caused you to make this change?

**Comment by jclausen** [comment]
@sanaullah Your PR has been merged in to development.  Thanks for all of your hard work!  :)

**Comment by sanaullah** [comment]
Thanks Jon, I will keep improving CF11 compatibility... Please let me know if there any changes you may like to add/adjust.

**Comment by jclausen** [comment]
Great!  My biggest suggestion for contributions to OSS would be that, when you move files around in directories, to use `git mv` instead of the GUI.   This allows the file history to be tracked.  

This was a challenging merge because Git was confused about whether the file was being renamed, created, or deleted and so the merge strategy had to be evaluated on a file-by-file basis.  If you use the internal Git file operators, auto-merging the PR should be relatively easy.

**Pull request merged**
