### PR TITLE
CF 9/10 syntax compatibilty, with some tweaks

### PR DESCRIPTION
**Pull request by sanaullah**
CF 9/10 syntax compatibilty, with some tweaks

### CODE REVIEW

**Comment by jclausen** [comment]
Thanks for the PR @sanaullah and for catching my code smells!  I've got to make sure I start testing on ACF before I push changes to master.  :+1:

**Comment by sanaullah** [comment]
Hi, 

Few suggestion, if you layout code base like https://github.com/ColdBox/cbox-i18n 

App
-- config
-- handlers
-- models
-- tests
-- modues
------ cbmongodb

So tests and other stuff can live separately. So it will look like more real app with module, which can inherit config/coldbox.cfc settings for cfmongodb.

**Comment by jclausen** [comment]
Thanks @sanaullah .  I have converting it to use the Coldbox module template (https://github.com/ColdBox/cbox-module-template - which is what i18n uses) planned in the near future.  

I need to find time to get a CI release build process setup for the module itself, because doing so will break all of my existing links and will require a separate download server from GitHub for Commandbox installs

Thanks again! - J

**Comment by sanaullah** [comment]
Thanks for replying so quickly, is it possible to if you start new git-repo with name "cbox-cbmongodb". I can help you in moving module code and  tests

**Comment by jclausen** [comment]
I'll probably keep the same repo, to keep the issues, wiki, and PR change history.  The tests should port over without problem.  You just have to add `this.loadColdbox=true` to the base tests classes, since they will no longer run from within the module handler.

The issue is the release build process.  Currently Forgebox uses the .zip download link for the master branch from Github for the module installation.  The build process will have to change so that modules/cbmongodb is zipped up, and pushed up to AWS for download.

If you feel like helping out, that'd be great!  Use the module template link referenced above and find/replace `cbjavaloader` with `cbmongodb`.    

Go ahead and push your PR to the development branch, _**not**_ the master.  When you refactor, just use `git mv ...` to move things around and the merge should be easy.   I can then configure the CI build process.  Once that's set up, I'll replace the master branch with the module template version.

**Comment by jclausen** [comment]
I should note, you'll want to keep upstream tracking for the dev branch.  I have some changes in there that aren't vetted, which will be in an upcoming patch this week or early next.

**Comment by jclausen** [comment]
Epic Link on Pivotal Tracker:  https://www.pivotaltracker.com/epic/show/2320161

**Comment by sanaullah** [comment]
Hi,

I have stated porting into module-template and will push changes to **development**  branch as soon all unit tests passed.

**Pull request merged**
